# Generated by Django 3.0.8 on 2020-08-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomno', models.IntegerField()),
                ('occopied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomno', models.IntegerField()),
                ('occopied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RNac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomno', models.IntegerField()),
                ('occopied', models.BooleanField(default=False)),
            ],
        ),
    ]
